language: php
os: linux

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - php: 7.1
      env: ILLUMINATE_VERSION=5.5.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.6.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.7.*
    - php: 7.1
      env: ILLUMINATE_VERSION=5.8.*
    - php: 7.2
      env: ILLUMINATE_VERSION=6.*
    - php: 7.2
      env: ILLUMINATE_VERSION=7.*
    - php: 7.3
      env: ILLUMINATE_VERSION=8.*

before_install:
  - composer require illuminate/notifications:"${ILLUMINATE_VERSION}" illuminate/support:"${ILLUMINATE_VERSION}" --no-update
  - composer require illuminate/database:"${ILLUMINATE_VERSION}" illuminate/queue:"${ILLUMINATE_VERSION}" --dev --no-update

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
